version: '3.8'

services:
  # Aplicação principal
  app:
    build: .
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=development
      - DB_HOST=stockc-db-1
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=stock_control
      - DB_PORT=3306
      - JWT_SECRET=seu-segredo-super-secreto-mude-depois
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./logs:/app/logs
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - stockctrl-network
    restart: unless-stopped

  # Banco de dados MySQL
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stock_control
      - MYSQL_USER=stockctrl
      - MYSQL_PASSWORD=stockctrl123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stockctrl-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stockctrl-network
    restart: unless-stopped

  # phpMyAdmin para gerenciar o banco (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - stockctrl-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  stockctrl-network:
    driver: bridge 